NAME = libft.a

CC = gcc

SOURCE = ft_strlcpy.c ft_....

OBJECTS = (.c = .o) ???

FLAGS = -Wall -Wextra -Werror

all: $(NAME)

$(NAME) =  
	ar -rc $(NAME) $(OBJECTS)

clean:

fclean:

re:

PHONY: all clean fclean re
